version: '3.8'

services:
  attacker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inquisitor
    networks:
      lan:
        ipv4_address: 10.5.0.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true

  victim:
    image: stilliard/pure-ftpd
    container_name: victim
    networks:
      lan:
        ipv4_address: 10.5.0.20
    environment:
      FTP_USER_NAME: tauer
      FTP_USER_PASS: pass
      FTP_USER_HOME: /home/ftpusers/tauer
    volumes:
      - ftpdata:/home/ftpusers/tauer
    command: ["/bin/sh", "-c", "pure-ftpd -u 1 -E -j -R -P 10.5.0.20 -p 30000:30009"]
    stdin_open: true
    tty: true

  ftp-client:
    build:
      context: .
      dockerfile: Dockerfile.ftp-client
    container_name: ftp-client
    networks:
      lan:
        ipv4_address: 10.5.0.30
    tty: true

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

volumes:
  ftpdata:
