# Dockerfile.ftp-client
FROM alpine

RUN apk update && apk add --no-cache lftp && rm -rf /var/cache/apk/*

RUN echo "test depuis le client" > /test.txt

COPY ftp-script.txt /ftp-script.txt

CMD ["/bin/sh", "-c", "lftp -c \"open tauer:eheh@10.5.0.20; put /test.txt; ls; bye\" && exec sh"]