version: '3.8'

services:
  attacker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inquisitor
    networks:
      lan:
        ipv4_address: 10.5.0.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true

  victim:
      # image: stilliard/pure-ftpd # REMOVE this line
      build:
        context: .
        dockerfile: Dockerfile.victim # ADD this line to use your custom Dockerfile
      container_name: victim
      networks:
        lan:
          ipv4_address: 10.5.0.20
      environment:
        FTP_USER_NAME: tauer
        FTP_USER_PASS: eheh
        FTP_USER_HOME: /home/ftpusers/tauer
      volumes:
        - ftpdata:/home/ftpusers/tauer
      command: ["pure-ftpd", "-A", "-P", "10.5.0.20", "-p", "30000:30009", "-j", "-R"]
      stdin_open: true
      tty: true
      healthcheck:
        test: ["CMD", "nc", "-zv", "10.5.0.20", "21"] # CHANGE to use nc
        interval: 5s
        timeout: 3s
        retries: 5
        start_period: 10s

  ftp-client:
    build:
      context: .
      dockerfile: Dockerfile.ftp-client
    container_name: ftp-client
    networks:
      lan:
        ipv4_address: 10.5.0.30
    tty: true
    # --- ADD THIS DEPENDS_ON BLOCK ---
    depends_on:
      victim:
        condition: service_healthy

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

volumes:
  ftpdata:
