# docker-compose.yml
version: '3.8'

services:
  ftp_server:
    build: .
    container_name: ftp_server
    ports:
      - "21:21"
      - "20:20"
      - "21000-21010:21000-21010"
    volumes:
      - ./data:/home/ftpuser/ftp_data
    networks:
      - inquisitor_net

  inquisitor:
    build: ./inquisitor.py # Path to your inquisitor Dockerfile/code
    container_name: inquisitor
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - inquisitor_net
    volumes:
      - ./inquisitor.py:/app # Mount your inquisitor code into the container
    # --- MODIFICATION START ---
    # Override the default command to keep the container running but idle
    command: tail -f /dev/null
    # --- MODIFICATION END ---
    # If you need environment variables to be set when you manually run your program:
    environment:
      # These won't be used by the 'command' above, but will be set
      # as environment variables for any process you launch manually in the container.
      # You'll still need to get the correct IPs for your specific setup.
      FTP_SERVER_IP: "172.18.0.2" # Example: Get this from docker inspect ftp_server
      GATEWAY_IP: "172.18.0.1" # Example: Get this from docker network inspect inquisitor_net
      # If your inquisitor program can read from environment variables, you can use these.
      # Otherwise, you'll type the IPs manually when you execute your program.

networks:
  inquisitor_net:
    driver: bridge