version: '3.8'

services:
  ftp_server:
    build: .
    container_name: ftp_server
    ports:
      - "21:21"
      - "20:20"
      - "21000-21010:21000-21010"
    volumes:
      - ./data:/home/ftpuser/ftp_data
    networks:
      - inquisitor_net

  inquisitor:
    build: ./inquisitor
    container_name: inquisitor
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - inquisitor_net
    volumes:
      - ./inquisitor:/app
    command: tail -f /dev/null
    environment:
     

      FTP_SERVER_IP: "172.18.0.2" 
      GATEWAY_IP: "172.17.0.1" 
      
    sysctls:
      net.ipv4.ip_forward: 1
networks:
  inquisitor_net:
    driver: bridge