# docker-compose.yml
version: '3.8'

services:
  ftp_server:
    build: .
    container_name: ftp_server
    ports:
      - "21:21"
      - "20:20"
      - "21000-21010:21000-21010" # Passive mode port range
    volumes:
      - ./data:/home/ftpuser/ftp_data # Mount a local directory for FTP files
    networks:
      - inquisitor_net

  # You can add your inquisitor container here if it's Dockerized
  # inquisitor:
  #   build: ./your_inquisitor_program
  #   container_name: inquisitor
  #   cap_add:
  #     - NET_ADMIN # Required for raw sockets and network manipulation
  #     - NET_RAW
  #   network_mode: service:ftp_server # This makes it share the network stack with ftp_server
  #   # OR
  #   # networks:
  #   #   - inquisitor_net
  #   # And then you'd need to configure it to target ftp_server's IP within the network
  #   # environment:
  #   #   FTP_SERVER_IP: ftp_server
  #   #   ... your other parameters
  #   command: python /app/inquisitor.py -h ftp_server -g <gateway_ip> -t <target_ip> -i <interface>

networks:
  inquisitor_net:
    driver: bridge