FROM alpine

RUN apk update && apk add --no-cache inetutils-ftp

RUN echo "test depuis le client" > /test.txt

COPY ftp-script.txt /ftp-script.txt

CMD ["/bin/sh", "-c", "ftp -n -v 10.5.0.20 < /ftp-script.txt && exec sh"]
